### ISSUE TITLE
is this handling wrong file name with proper message?

### ISSUE THREAD

**Issue by broxmapyo007** [nandu-k01/Test#1]
1. if possible do testing with negative cases once

**Comment by nandu-k01** [comment]
I just updated the code to except FileNotFoundError, would that be enough or should i update it to expect errors in startline and endline

**Comment by broxmapyo007** [comment]
i would suggest to use ignkre files and comments for function and handle
missing files it added good review.

**Comment by nandu-k01** [comment]
i have added the comments, i did not understand what you meant in the first line

**Comment by nandu-k01** [comment]
included .gitignore
